version: "3"

services:
  planning-poker:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    container_name: planning-poker
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
    volumes:
      - ./public:/app/public
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
